#+title: Adelfa Web Page

Some links to University IT information about web pages:
  - Guide for planning and managing a web site
    https://it.umn.edu/services-technologies/self-help-guides/content-strategy-plan-maintain-website
  - Comparisons of tools available for creating web sites
    https://it.umn.edu/services-technologies/comparisons/compare-tools-create-website


* what are the goals for the web site?
  1. provide access to the Adelfa system
  2. provide an basic understanding of what Adelfa is and what it is
     used for
  3. educate on how Adelfa is used and what its capabilities are
  4. collect all content and work relating to the system in once
     accessible location


* contents
** brief description of what the system is
  This description should highlight the interesting features of Adelfa
  and what sort of reasoning it is used for.

  This description is in file [[file:/cygdrive/c/Users/Poffalina/Documents/sparrow/systems/LF-Reasoning/system_description.txt][system description]]



** link to a brief introduction to/tutorial for the system
  This could start with the text in the [[file:/cygdrive/c/Users/Poffalina/Documents/sparrow/systems/LF-Reasoning/sample_interaction.txt][sample interaction]].


** reference guide/users manual with all the syntax and such
  This could start with the [[file:/cygdrive/c/Users/Poffalina/Documents/sparrow/systems/LF-Reasoning/system_reference.txt][system reference]] I wrote though it should
  be updated and checked for accuracy.
  Eventually having a more easy to navigate format would be ideal
  and will want to make it more modularized.


** download link for source
** TODO clean up source files
** TODO verify build/installation instructions
** TODO determine where and how to host the code
   related: some sort of bug tracking system


** a list of examples with descriptions
  eventually we might try to display them like on the Abella page

  1. Type Uniqueness
  2. Cut Elimination
  3. Transitivity and Narrowing for F-sub (Poplmark challenge problem)
  4. Identity element for addition
  5. properties of lists (Daniel's work)

     
** a listing of publications relating to the work, with links


** acknowledgments/funding information



* phased plan
** phase 1: publish code on github
   The first step will be to make the system available by putting the
   code on github.
** phase 2: create a web page with essential content
   After the code is made a available the next phase would be to
   create a basic page for Adelfa which contains essential information
   about the system and where to get it. This phase will result in a
   functioning web page which facilitates the most basic requirement
   of the web site: it tells you what the system is about and lets you
   access the github repository for the system.

   What are the essential contents?
   - system name and description
   - link to the source code
   - acknowledgments/funding statement
** phase 3: Elaborating Content of the Web Page
   In this phase we extend the content available on the web page to
   include information which is intended to give users some
   guidance in how to use the system for reasoning.

   To be added in this phase:
   - basic users guide
   - sample interaction
   - enumeration of examples and brief descriptions
   - list of publications (or pending submissions) relating to the system
** phase 4: ongoing upkeep/revisions
   In this final phase the contents as currently envisaged are
   complete, but can be extended with more examples, publications,
   etc. as they are developed.
