name: Build & Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - "5.1"
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up OCaml ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v2.2.6
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest